### PR TITLE
Fix #214. Add localized link for the navbar brand.

### LINKED ISSUE #214: Hardfork brand link broken
The "HARDFORK" brand link in the navbar is broken. It should link to the landingpage. 
Currently nothing happens when clicking on it.

### PR DESCRIPTION
**Pull request by kiliw**
Fix #214. 
Add localized link for the navbar brand. If a user clicks now on the brand logo in the navbar she is linked back to the correct home depending on here language.

### CODE REVIEW

File: src/components/Navbar/index.tsx [hunk 1]
```diff
@@ -40,9 +41,9 @@ export const NavbarComponent: FunctionComponent<NavbarComponentProps> = ({
       dark
       expand="md"
     >
-      <NavbarBrand tag={linkTag} to="/">
+      <LocalizedLink Component={linkTag} to="/" className="navbar-brand">
```
Comment (Levino) [inline src/components/Navbar/index.tsx]:
```suggestion
      <NavbarBrand tag={LocalizedLink(linkTag)} to="/">
```
